baseURL = 'https://alk-zwolle.nl/'
languageCode = 'nl'
title = 'ALK Netwerk Kinderfysiotherapie'
theme = 'alk-theme'

[params]
  description = 'ALK Netwerk voor Kinderfysiotherapie - Hulp bij aanhoudende lichamelijke klachten'
  author = 'ALK Netwerk'

[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = 'Bij welke klachten'
    url = '/bij-welke-klachten/'
    weight = 2
  [[menu.main]]
    name = 'Over ons'
    url = '/over-ons/'
    weight = 3
  [[menu.main]]
    name = 'Zoek een kinderfysiotherapeut'
    url = '/zoek-kinderfysiotherapeut/'
    weight = 4
